name: Build Python Wheel

on:
  workflow_dispatch:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clean previous builds
        run: |
          rm -rf dist build *.egg-info

      - name: Install packaging tools
        run: |
          python -m pip install --upgrade pip build wheel setuptools

      - name: Build wheel (prefers pyproject.toml)
        run: |
          if [ -f "pyproject.toml" ]; then
            python -m build --wheel
          elif [ -f "setup.py" ]; then
            python setup.py bdist_wheel
          else
            echo "No setup.py or pyproject.toml found!" && exit 1
          fi

      - name: List whl files created
        run: ls -lh dist/

      - name: Upload wheel file(s)
        uses: actions/upload-artifact@v4
        with:
          name: wheel-files
          path: dist/*.whl
